<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
	<title><!--{chrTitle}--></title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<link rel="stylesheet" type="text/css" href="/css/green.css" />
	<link rel="stylesheet" type="text/css" href="/css/forms.css" />
	<script type="text/javascript" src="/js/google.js"></script>
	<script type="text/javascript" src="/js/focus.js"></script>
</head>
<body>
	<div id="header">
		<div id="header_inner">
			<div style="float: right"><!--{chrLogout}--></div>
			<div style="float: left">
				<h1><a href="/"><!--{chrTitle}--></a></h1>
				<!--<div id="slogan"><!--{chrSubtitle}--></div>-->
			</div>
		</div>
	</div>
	<div id="main">
		<div id="rcol">
			<div id="rcontent">
				<h1><!--{chrPageTitle}--></h1>
				<span id="slogan2"><!--{chrPageSubtitle}--></span>
				<!--{chrBody}-->
				<div class="summary"><!--{chrSummary}--></div>
			</div>
		</div>
	</div>
	<div id="footer">
		<!--{chrFooter}-->
	</div>
</body>
</html>
